# Rote Punkte Zeichnen mit q Beenden

In [2]:
import cv2

path = 'Gesicht.jpg'  #Dateipfad des Bildes
img = cv2.imread(path) #Bild einlesen

#draw point with mouse in the picture
def DrawPoint(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN: #Wenn linke Maustaste gedrückt wurde
        cv2.circle(img, center=(x,y), radius=0, color=(0,0,255), thickness=5) #roten Kreis an die stelle des Mauszeigers Zeichnen

#Punkt zeichnen
cv2.namedWindow(winname = 'image')
cv2.setMouseCallback('image',DrawPoint)  #Funktion für den Mausinterrupt 

while(1):
    cv2.imshow('image',img)  #Ausgabe des Image in einer Unendlichen Schleife
    if cv2.waitKey(20) == ord('q'):  #Abbruch mit der Taste q
        break
cv2.destroyAllWindows()

# Polynom mit Mindestens 3 Punkten erzeugen

In [4]:
import cv2
import numpy as np

# Open the image file
img = cv2.imread('Gesicht.jpg')

# Set up the mouse callback function
def draw_circle(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img,(x,y),3,(0,0,255),-1)
        points.append((x,y))
        print(points)
        if len(points) > 2:
            cv2.polylines(img, [np.array(points)], True, (0, 255, 0), thickness=2) #image, liste aus Punkten in zweier Tupel, soll das Polygon geschlossen werden, Farbe, dicke Linie

def Cutout():
    print("Test")
    ## (2) make mask
    pts = np.array(points)
    mask = np.zeros(img.shape[:2], np.uint8)
    cv2.drawContours(mask, [pts], -1, (255, 255, 255), -1, cv2.LINE_AA)

    ## (3) do bit-op
    test = cv2.bitwise_and(img, img, mask=mask)
    cv2.imwrite("test.png", test)

# Set up the window and callback
cv2.namedWindow('image')
cv2.setMouseCallback('image',draw_circle)
points = []

# Loop to display the image and wait for events
while True:
    cv2.imshow('image',img)  #Ausgabe des Image in einer Unendlichen Schleife
    
    if cv2.waitKey(20) == ord('q'):  #Abbruch mit der Taste q
        break

    if cv2.waitKey(20) == ord('c'):  #Abbruch mit der Taste q
        Cutout()

cv2.destroyAllWindows()

[(179, 93)]
[(179, 93), (253, 275)]
[(179, 93), (253, 275), (472, 245)]
[(179, 93), (253, 275), (472, 245), (388, 91)]
Test
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
# 2018.01.17 20:39:17 CST
# 2018.01.17 20:50:35 CST
import numpy as np
import cv2

img = cv2.imread("Robot.png")
pts = np.array([[10,150],[150,100],[300,150],[350,100],[310,20],[35,10]])

## (1) Crop the bounding rect
rect = cv2.boundingRect(pts)
x,y,w,h = rect
croped = img[y:y+h, x:x+w].copy()

## (2) make mask
pts = pts - pts.min(axis=0)

mask = np.zeros(croped.shape[:2], np.uint8)
print(mask)
cv2.drawContours(mask, [pts], -1, (255, 255, 255), -1, cv2.LINE_AA)
print(mask)

## (3) do bit-op
dst = cv2.bitwise_and(croped, croped, mask=mask)

## (4) add the white background
bg = np.ones_like(croped, np.uint8)*255
cv2.bitwise_not(bg,bg, mask=mask)
dst2 = bg+ dst


cv2.imwrite("croped.png", croped)
cv2.imwrite("mask.png", mask)
cv2.imwrite("dst.png", dst)
cv2.imwrite("dst2.png", dst2)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [206 255 255 ...   0   0   0]
 [230 255 255 ...   0   0   0]
 [213 216 132 ...   0   0   0]]


True