# Rote Punkte Zeichnen mit q Beenden

In [2]:
import cv2

path = 'Gesicht.jpg'  #Dateipfad des Bildes
img = cv2.imread(path) #Bild einlesen

#draw point with mouse in the picture
def DrawPoint(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN: #Wenn linke Maustaste gedrückt wurde
        cv2.circle(img, center=(x,y), radius=0, color=(0,0,255), thickness=5) #roten Kreis an die stelle des Mauszeigers Zeichnen

#Punkt zeichnen
cv2.namedWindow(winname = 'image')
cv2.setMouseCallback('image',DrawPoint)  #Funktion für den Mausinterrupt 

while(1):
    cv2.imshow('image',img)  #Ausgabe des Image in einer Unendlichen Schleife
    if cv2.waitKey(20) == ord('q'):  #Abbruch mit der Taste q
        break
cv2.destroyAllWindows()

# Polynom mit Mindestens 3 Punkten erzeugen

In [2]:
import cv2
import numpy as np

# Open the image file
img = cv2.imread('Gesicht.jpg')

# Set up the mouse callback function
def draw_circle(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img,(x,y),3,(0,0,255),-1)    #punkt erzeugen
        points.append((x,y))    #Punkte die angelickt wurden speichern
        print(points)
        if len(points) > 2:
            cv2.polylines(img, [np.array(points)], False, (0, 255, 0), thickness=2) #image, liste aus Punkten in zweier Tupel, soll das Polygon geschlossen werden, Farbe, dicke Linie

def Cutout():
    pts = np.array(points)   #np Array aus den Punkten des Polygon erstellen
    mask = np.zeros(img.shape[:2], np.uint8) #Maske erzeugen aus den Punkten
    cv2.drawContours(mask, [pts], -1, (255, 255, 255), -1, cv2.LINE_AA) #Konturen zeichnen

    cutImg = cv2.bitwise_and(img, img, mask=mask)  #Bildbereich ausschneiden
    cv2.imwrite("Cut Image.png", cutImg)    #Ausgeschnittenes Bild speichern

    # Erstelle ein neues Bild mit einem leeren Alphakanal
    cutImgWithAlpha = cv2.cvtColor(cutImg, cv2.COLOR_BGR2BGRA)
    cutImgWithAlpha[:, :, 3] = mask #Maske auf das neue Bild mir Alphakanal anwenden

    # Erstelle ein neues Bild mit einem leeren Alphakanal im Hintergrund
    background = np.zeros((img.shape[0], img.shape[1], 4), dtype=np.uint8)

    # Invertiere die Maske, um das ausgeschnittene Gesicht transparent zu machen
    mask_inv = cv2.bitwise_not(mask)

    # Verwende die Maske, um den Hintergrund transparent zu machen
    background[mask_inv == 255] = [0, 0, 0, 0]

    # Füge das ausgeschnittene Gesicht zum Hintergrund hinzu
    finalImg = cv2.add(background, cutImgWithAlpha)
    cv2.imwrite("Final Image.png", finalImg)

# Neues Ausgabe Window erzeugen
cv2.namedWindow('image')
cv2.setMouseCallback('image',draw_circle)
points = [] #Liste um Punkte des Polygones zu speichern

# Loop das die Tasten abfrägt
while True:
    cv2.imshow('image',img)  #Ausgabe des Image in einer Unendlichen Schleife
    
    if cv2.waitKey(1) == ord('q'):  #Abbruch mit der Taste q
        break

    if cv2.waitKey(1) == ord('c'):  #Ausschneiden und Speichern des Bereichs mit der Taste c 
        Cutout()

cv2.destroyAllWindows()   #Anwendung beenden

QObject::moveToThread: Current thread (0x19b4e40) is not the object's thread (0x1cd0a40).
Cannot move to target thread (0x19b4e40)

QObject::moveToThread: Current thread (0x19b4e40) is not the object's thread (0x1cd0a40).
Cannot move to target thread (0x19b4e40)

QObject::moveToThread: Current thread (0x19b4e40) is not the object's thread (0x1cd0a40).
Cannot move to target thread (0x19b4e40)

QObject::moveToThread: Current thread (0x19b4e40) is not the object's thread (0x1cd0a40).
Cannot move to target thread (0x19b4e40)

QObject::moveToThread: Current thread (0x19b4e40) is not the object's thread (0x1cd0a40).
Cannot move to target thread (0x19b4e40)

QObject::moveToThread: Current thread (0x19b4e40) is not the object's thread (0x1cd0a40).
Cannot move to target thread (0x19b4e40)

QObject::moveToThread: Current thread (0x19b4e40) is not the object's thread (0x1cd0a40).
Cannot move to target thread (0x19b4e40)

QObject::moveToThread: Current thread (0x19b4e40) is not the object's thread

In [5]:
# 2018.01.17 20:39:17 CST
# 2018.01.17 20:50:35 CST
import numpy as np
import cv2

img = cv2.imread("Robot.png")
pts = np.array([[10,150],[150,100],[300,150],[350,100],[310,20],[35,10]])

## (1) Crop the bounding rect
rect = cv2.boundingRect(pts)
x,y,w,h = rect
croped = img[y:y+h, x:x+w].copy()

## (2) make mask
pts = pts - pts.min(axis=0)

mask = np.zeros(croped.shape[:2], np.uint8)
print(mask)
cv2.drawContours(mask, [pts], -1, (255, 255, 255), -1, cv2.LINE_AA)
print(mask)

## (3) do bit-op
dst = cv2.bitwise_and(croped, croped, mask=mask)

## (4) add the white background
bg = np.ones_like(croped, np.uint8)*255
cv2.bitwise_not(bg,bg, mask=mask)
dst2 = bg+ dst


cv2.imwrite("croped.png", croped)
cv2.imwrite("mask.png", mask)
cv2.imwrite("dst.png", dst)
cv2.imwrite("dst2.png", dst2)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [206 255 255 ...   0   0   0]
 [230 255 255 ...   0   0   0]
 [213 216 132 ...   0   0   0]]


True